title: "Schaakclub Jean Jaurès"
description: "De schaakclub van Gent sinds 1945"
baseurl: "/schaakclub-jean-jaures"
url: "https://jruyssinck.github.io"
theme: null

collections:
  news:
    output: true
    permalink: /:collection/:path/
  results:
    output: false
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "nl"
    values:
      lang: nl
  - scope:
      path: "en"
    values:
      lang: en
  - scope:
      path: ""
      type: "news"
    values:
      layout: news-item

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - docs
  - vendor
  - node_modules
